set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

# Digilent Cmod-A7 on-board resources
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports reset_in]
set_property PACKAGE_PIN A18 [get_ports reset_in]
set_property PACKAGE_PIN L17 [get_ports clk_in]

# ELF-CMOD-A7 board resources
set_property IOSTANDARD LVCMOS33 [get_ports {led_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports led_dh_latch]
set_property IOSTANDARD LVCMOS33 [get_ports led_dl_latch]
set_property IOSTANDARD LVCMOS33 [get_ports led_d_blank]
set_property IOSTANDARD LVCMOS33 [get_ports led_a3_latch]
set_property IOSTANDARD LVCMOS33 [get_ports led_a2_latch]
set_property IOSTANDARD LVCMOS33 [get_ports led_a32_blank]
set_property IOSTANDARD LVCMOS33 [get_ports led_a1_latch]
set_property IOSTANDARD LVCMOS33 [get_ports led_a0_latch]
set_property IOSTANDARD LVCMOS33 [get_ports led_a10_blank]
set_property IOSTANDARD LVCMOS33 [get_ports led_q]

set_property PACKAGE_PIN W7  [get_ports {led_d[3]}]
set_property PACKAGE_PIN U3  [get_ports {led_d[2]}]
set_property PACKAGE_PIN U2  [get_ports {led_d[1]}]
set_property PACKAGE_PIN W6  [get_ports {led_d[0]}]
set_property PACKAGE_PIN V4  [get_ports led_dh_latch]
set_property PACKAGE_PIN W5  [get_ports led_dl_latch]
set_property PACKAGE_PIN U4  [get_ports led_d_blank]
set_property PACKAGE_PIN U7  [get_ports led_a3_latch]
set_property PACKAGE_PIN U8  [get_ports led_a2_latch]
set_property PACKAGE_PIN V8  [get_ports led_a32_blank]
set_property PACKAGE_PIN W4  [get_ports led_a1_latch]
set_property PACKAGE_PIN V5  [get_ports led_a0_latch]
set_property PACKAGE_PIN U5  [get_ports led_a10_blank]
set_property PACKAGE_PIN V3  [get_ports led_q]

set_property IOSTANDARD LVCMOS33 [get_ports sw_input_nc_n]
set_property IOSTANDARD LVCMOS33 [get_ports sw_load_nc_n]
set_property IOSTANDARD LVCMOS33 [get_ports sw_mp_n]
set_property IOSTANDARD LVCMOS33 [get_ports sw_run]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_d[0]}]

set_property PULLUP true [get_ports sw_input_nc_n]
set_property PULLUP true [get_ports sw_load_nc_n]
set_property PULLUP true [get_ports sw_mp_n]
set_property PULLUP true [get_ports sw_run]
set_property PULLUP true [get_ports {sw_d[7]}]
set_property PULLUP true [get_ports {sw_d[6]}]
set_property PULLUP true [get_ports {sw_d[5]}]
set_property PULLUP true [get_ports {sw_d[4]}]
set_property PULLUP true [get_ports {sw_d[3]}]
set_property PULLUP true [get_ports {sw_d[2]}]
set_property PULLUP true [get_ports {sw_d[1]}]
set_property PULLUP true [get_ports {sw_d[0]}]

set_property PACKAGE_PIN K2  [get_ports sw_input_nc_n]
set_property PACKAGE_PIN A16 [get_ports sw_load_nc_n]
set_property PACKAGE_PIN V2  [get_ports sw_mp_n]
set_property PACKAGE_PIN U1  [get_ports sw_run]
set_property PACKAGE_PIN K3  [get_ports {sw_d[7]}]
set_property PACKAGE_PIN C15 [get_ports {sw_d[6]}]
set_property PACKAGE_PIN M3  [get_ports {sw_d[5]}]
set_property PACKAGE_PIN L2  [get_ports {sw_d[4]}]
set_property PACKAGE_PIN N2  [get_ports {sw_d[3]}]
set_property PACKAGE_PIN M1  [get_ports {sw_d[2]}]
set_property PACKAGE_PIN W2  [get_ports {sw_d[1]}]
set_property PACKAGE_PIN W3  [get_ports {sw_d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports csync_n]
set_property IOSTANDARD LVCMOS33 [get_ports video]

set_property PACKAGE_PIN P1  [get_ports video]
set_property PACKAGE_PIN R3  [get_ports csync_n]

set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rts_n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_cts_n]

set_property PACKAGE_PIN N1  [get_ports uart_txd]
set_property PACKAGE_PIN R2  [get_ports uart_rxd]
set_property PACKAGE_PIN T3  [get_ports uart_rts_n]
set_property PACKAGE_PIN H2  [get_ports uart_cts_n]

