set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVDS_25} [get_ports i_100MHz_N]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVDS_25} [get_ports i_100MHz_P]
create_clock -name {clk100}  [get_ports {i_100MHz_P}] -period {10.000}  -add 

set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVTTL} [get_ports RESET_N]

set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVTTL} [get_ports UART1_CTS_N]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVTTL} [get_ports UART1_RTS_N]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVTTL} [get_ports UART1_RXD]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVTTL} [get_ports UART1_TXD]

set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVTTL} [get_ports led_q]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVTTL} [get_ports led_spare]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVTTL} [get_ports led_d_le_n]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVTTL} [get_ports led_d_bl]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVTTL} [get_ports led_al_le_n]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVTTL} [get_ports led_al_bl]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVTTL} [get_ports led_ah_le_n]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVTTL} [get_ports led_ah_bl]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVTTL} [get_ports {led_d[7]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVTTL} [get_ports {led_d[6]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVTTL} [get_ports {led_d[5]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVTTL} [get_ports {led_d[4]}]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVTTL} [get_ports {led_d[3]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVTTL} [get_ports {led_d[2]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVTTL} [get_ports {led_d[1]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVTTL} [get_ports {led_d[0]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVTTL} [get_ports {led_a[7]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVTTL} [get_ports {led_a[6]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVTTL} [get_ports {led_a[5]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVTTL} [get_ports {led_a[4]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVTTL} [get_ports {led_a[3]}]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVTTL} [get_ports {led_a[2]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVTTL} [get_ports {led_a[1]}]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVTTL} [get_ports {led_a[0]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVTTL} [get_ports {led_a[15]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVTTL} [get_ports {led_a[14]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVTTL} [get_ports {led_a[13]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVTTL} [get_ports {led_a[12]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVTTL} [get_ports {led_a[11]}]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVTTL} [get_ports {led_a[10]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVTTL} [get_ports {led_a[9]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVTTL} [get_ports {led_a[8]}]

set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[7]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_load_nc_n}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[6]}]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[5]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_input_nc_n}]
#     sw_input_nc_n (DIN C26) is L16 for 7a100t board, K19 for 7a102t board
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[4]}]
#     sw_input_no_n (DIN C27) is M16 for 7a100t board, L16 for 7a102t board
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[3]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[2]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[1]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_run}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_d[0]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVTTL PULLUP TRUE} [get_ports {sw_mp_n}]

#eof
